# Welcome to Jekyll!


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: LiangChengDeYe
SEOTitle:  LiangChengDeYe | LiangChengDeYe's Blog
header-img: img/home-bg.jpg
email: 415900617@QQ.com
description: "欢迎来到我的个人博客"
keywords: "吴浩杰, 博客，Java，IT，Python，爬虫"
baseurl: ""
url: "https://liangchengdeye.github.io"
permalink: /:year/:month/:day/:title/
# Author 
author: "LiangChengDeYe"

# SNS settings

github_username:  Liangchengdeye
github_link: https://github.com/Liangchengdeye?tab=repositories
email: 415900617@qq.com
weibo_username: /u/5406340504
zhihu_username: liang-cheng-de-ye/activities
description_footer: 吴浩杰个人专栏！
csdn_link: https://blog.csdn.net/sinat_32651363
jianshu_link: https://www.jianshu.com/u/ad41238ebf6e
wangyi_link: https://music.163.com/#/user/home?id=299964197
# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 00f396a2922bd4d7660cb3f9208c96d9

# Comments   
disqus_username: Liangchengdeye


# Build settings
# permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
theme: minima
gems: [jekyll-paginate]

paginate: 8


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "人生苦短，但生活有趣呀！"
sidebar-avatar: /img/avatar-ling.jpg


exclude:
  - Gemfile
  - Gemfile.lock

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1


# Friends
friends: [
    {
        title: "咕咚",
        href: "http://gudong.name/"
    },{
        title: "Lusheep",
        href: "http://lusheep.me/"
    },{
        title: "晨风明悟",
        href: "http://www.cfmwsc.cn/"
    },{
        title: "VeryNice",
        href: "http://very9s.net/"
    },{
        title: "HyG",
        href: "https://gaohaoyang.github.io/?from=inf&wvr=5&loc=infblog"
    },{
       title: "雷全的个人网站",
       href: "https://leiquan.website/"
    
     },{
       title: "Yipeng Qin",
       href: "http://yipengqin.com/"
    
     },{
       title: "Secret Blog",
       href: "https://blog.isecret.vip/"
     },{
       title: "Itgoyo",
       href: "https://itgoyo.github.io/gallery.html"
     },{
       title: "linglinyp",
       href: "http://linglinyp.com/"
     }

]
